# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_ahead'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: ahead

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dbt_ahead:
    # Config indicated by + and applies to all files under models/example/
    staging:
      salesforce:
        +schema: dsg_dw_stg
        +materialized: view
        +tag: salesforce_stg
    intermediate:
      +schema: dsg_dw_int
      +materialized: table
    modelled:
      +schema: dsg_dw_modl
      +materialized: table
    marts:
      +schema: dsg_dw_mart
      +materialized: table
    reports:
      +schema: dsg_dw_report
      +materialized: table
      #+post-hook: "grant select on {{ this }} to role dsg_analyst;"
seeds:
  +schema: dsg_dw_stg
