with source as (

    select * from {{ source('salesforce', 'product_2') }}

),

renamed as (

    select
        id AS salesforce_product_id,
        name AS product_name,
        product_code,
        description,
        quantity_schedule_type,
        quantity_installment_period,
        number_of_quantity_installments,
        revenue_schedule_type,
        revenue_installment_period,
        number_of_revenue_installments,
        is_active,
        created_date,
        created_by_id,
        last_modified_date,
        last_modified_by_id,
        system_modstamp,
        family AS product_family,
        currency_iso_code,
        external_id,
        display_url,
        quantity_unit_of_measure,
        is_deleted,
        is_archived,
        last_viewed_date,
        last_referenced_date,
        connection_received_id,
        connection_sent_id,
        stock_keeping_unit,
        product_line_c,
        manufacturer_c,
        default_term_months_c,
        cogs_c,
        infw_taxable_c,
        on_hand_c,
        quickbooks_id_c,
        quick_books_item_type_c,
        pse_is_services_product_c,
        is_asset_c,
        ahead_cost_c,
        customer_price_c,
        vendor_list_c,
        vendor_c,
        cost_method_c,
        item_type_c,
        purchasing_unit_c,
        ratio_to_oe_standard_c,
        ratio_to_po_standard_c,
        sales_unit_c,
        intacct_item_tax_group_c,
        asg_manufacturer_c,
        asg_product_c,
        budgetary_sku_c,
        ahd_solution_c,
        end_of_support_date_c,
        requores_sow_c,
        product_code_external_id_c,
        maintenance_category_c,
        solution_category_c,
        ela_c,
        in_intacct_c,
        tax_code_2_c,
        tax_code_description_c,
        po_description_c,
        so_description_c,
        product_specialty_team_c AS product_specialty_team,
        flag_c,
        cisco_recall_c,
        cisco_memory_price_increase_c,
        product_subcategory_c,
        service_brief_c,
        t_m_role_c,
        ahd_solution_category_c,
        services_product_description_c,
        pse_forecast_curve_c,
        cisco_price_change_new_gpl_del_c,
        cisco_price_change_may_2018_c,
        tax_code_changed_c,
        old_tax_code_c,
        new_tax_code_c,
        intacct_error_message_c,
        intacct_sync_status_c,
        changed_products_checkbox_c,
        l_1_sku_c,
        level_1_recommended_price_c,
        manufacturer_sku_c,
        kgrenewal_available_for_purchase_c,
        kgrenewal_available_quantity_c,
        kgrenewal_best_seller_score_c,
        kgrenewal_category_c,
        kgrenewal_create_assets_c,
        kgrenewal_do_not_capture_payment_at_checkout_c,
        kgrenewal_ecommerce_description_c,
        kgrenewal_ecommerce_name_c,
        kgrenewal_fourth_image_large_c,
        kgrenewal_fourth_image_med_c,
        kgrenewal_fourth_image_small_c,
        kgrenewal_is_featured_c,
        kgrenewal_is_product_bundle_parent_c,
        kgrenewal_is_replaced_by_c,
        kgrenewal_is_taxable_c,
        kgrenewal_low_quantity_level_c,
        kgrenewal_main_image_large_c,
        kgrenewal_main_image_med_c,
        kgrenewal_main_image_small_c,
        kgrenewal_percent_of_shipping_box_c,
        kgrenewal_price_term_type_c,
        kgrenewal_price_term_c,
        kgrenewal_quantity_type_c,
        kgrenewal_replacement_type_c,
        kgrenewal_second_image_large_c,
        kgrenewal_second_image_med_c,
        kgrenewal_second_image_small_c,
        kgrenewal_shipping_box_c,
        kgrenewal_shipping_weight_c,
        kgrenewal_subscription_c,
        kgrenewal_tax_code_c,
        kgrenewal_third_image_large_c,
        kgrenewal_third_image_med_c,
        kgrenewal_third_image_small_c,
        kgrenewal_e_commerce_enabled_c,
        unspsc_c,
        review_required_c,
        m_a_catalog_c,
        distributor_product_classification_c,
        legacy_id_c,
        model_number_c,
        legacy_ahead_practice_c,
        legacy_ahead_sub_practice_c,
        data_source_1_c,
        distributor_product_type_c,
        distributor_manufacturer_c,
        practice_c,
        _fivetran_synced,
        _fivetran_deleted,
        external_data_source_id,
        aws_sku_c,
        product_gla_override_c,
        practice_mirror_c,
        class_c

    from source

)

select * from renamed
